### ISSUE TITLE
Problem with slide change or drag slide in  RTL direction page

### ISSUE THREAD

**Issue by farshidpg** [k-ivan/tabs-slider#25]
Hello 
I have a website with 2 locale in English version(LTR) all right is ok but in Arabic/Persian/Kurdish version ( RTL ) design is ok but slider work with slide to left .

in RTL languages all things is RTL and user most slide ( drag , touch to right ) for change slides

for example owlcarousel2 handle this 

https://owlcarousel2.github.io/OwlCarousel2/demos/rtl.html

how i can handle RTL slide change in youre lib  ?

I have an idea for this like owlcarousel2 with  param in option "rtl" : true/false

**Comment by k-ivan** [comment]
Hello @farshidpg! 

Excellent suggestion. For example as an `rtl` option.

**Comment by k-ivan** [comment]
Hey @farshidpg! Please try version 3.1.1

I added the `rtl` option. You need to specify the `dir="rtl"` attribute on the tabs container or html|body, and call the plugin with the `rtl: true` option.

**Comment by farshidpg** [comment]
Tnx 👌🏼 I try v3

**Comment by farshidpg** [comment]
Excellent work , i tested and it works beautifully.

Without this option, I would have solved this issue in a difficult way :
In the RTL version, I read the database records in reverse and when loading the page, I used JavaScript to make the active slide minus one (the last slide) :)))

With this option, you revived me, brother ✌️  :)

**Comment by k-ivan** [comment]
Cool. Glad to help ;)
