### ISSUE TITLE
Lighthouse Best Practice error

### ISSUE THREAD

**Issue by nessor** [k-ivan/tabs-slider#5]
Lighthouse throws an best practice error for the tabSlider script.

![image](https://user-images.githubusercontent.com/3463261/87304986-06aa5500-c516-11ea-8d35-c3c5705ea18b.png)

The error is on line 306/307 wich are 

```javascript
      const dragEvent = this.dragEvent.event();
      this.content.addEventListener(dragEvent.start, this.handlerStart);
```

A recommendation can be found [here](https://web.dev/uses-passive-event-listeners/?utm_source=lighthouse&utm_medium=devtools#how-to-make-event-listeners-passive-to-improve-scrolling-performance)

**Comment by k-ivan** [comment]
Hi @nessor !
You're right, I'll add this option.

**Comment by nessor** [comment]
Cool! :) Thank you!

**Comment by k-ivan** [comment]
Updated to version 1.2.3

**Comment by nessor** [comment]
Perfect! Great, thanks! :) 

By the way: Cool package ;)

**Comment by k-ivan** [comment]
Thanks you!
